apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: python9424github
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python9424github 
  name: python9424github
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: python9424github
    weight: 100 
